spring:
  profiles: generatesql
  flyway:
    enabled: false
#  jpa.properties.javax.persistence.schema-generation.scripts:

  jpa.properties.javax.persistence.schema-generation.scripts:
    action: create
    create-target: create.sql
    create-source: metadata
  datasource.url: jdbc:postgresql://localhost:7432/springrecallbook
  datasource.username: admin
  datasource.password: pass123
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect


